### ISSUE TITLE
end user trying to get equalizer to work  ubuntu 19.10

### ISSUE THREAD

**Issue by mimitabby** [luqmana/rhythmbox-plugins#30]
![IMG-7313](https://user-images.githubusercontent.com/64096465/79896907-d0998100-83bd-11ea-8c87-970c4e63ceeb.JPG)
![IMG-7314](https://user-images.githubusercontent.com/64096465/79896910-d2634480-83bd-11ea-9802-7b5f1646015c.JPG)

i have successfully created a plug in folder in Rhythmbox.  It has equalizer in it and equalizer has the correct files in that. I tried to run install.sh following directions and while there were no error messages, nothing seemed to happen. I rebooted and then opened Rhythmbox and found the equalizer listed in the plug in list. I then tried to turn it on, but it doesn't turn on. I can toggle the switch, but the circle doesn't turn green and there's an x next to it. I THINK i added a file that shows this. Thanks very much for your help
![IMG-7312](https://user-images.githubusercontent.com/64096465/79895703-23723900-83bc-11ea-936d-82f17c0b3a00.JPG)

**Comment by hethhhhh** [comment]
same problem here

**Comment by avenkatakumar** [comment]
There should be one error message when enable to equalizer plugin.  when you move the cursor to x it will show the error message.  It is missing the dependency 'rb'.  'rb' is python module which is dependent for this plug in.  Are you able to find the 'rb.py' module?  I am also having the same issue.  Missing the 'rb.py'  If you found it please share that file.

**Comment by burnsaustin145** [comment]
I have the same issure right now on 18

**Comment by 14kaitou** [comment]
for rhythmbox version 3`./install.sh --rb3` before that install the dependencies posted at [README.](https://github.com/luqmana/rhythmbox-plugins/blob/master/README.md) 
the installation path `$HOME/.local/share/rhythmbox/plugins/ ` (for my prefix) if use sudo it will be in `/usr/local/rhythmbox/plugins/` the prefix path not affect anything only separated `~` `and /` grup directory

**Comment by avenkatakumar** [comment]
> for rhythmbox version 3`./install.sh --rb3` before that install the dependencies posted at [README.](https://github.com/luqmana/rhythmbox-plugins/blob/master/README.md)
> the installation path `$HOME/.local/share/rhythmbox/plugins/ ` (for my prefix) if use sudo it will be in `/usr/local/rhythmbox/plugins/` the prefix path not affect anything only separated `~` `and /` grup directory

I have tried to check the dependencies at README. But I am not able to see any dependencies.  Can you please guide me.  If you have the link for the dependencies, please post it.

If you are pointing me to rb-open-folder.py code, then if you had chance to see there is an import statement at first which is trying to import module "rb".  I am missing with that module.

**Comment by cdoersch** [comment]
Digging a little deeper into this, launching rhythmbox from the commandline gives the following error when the plugin is enabled: 

```** (rhythmbox:2635112): WARNING **: 00:28:44.477: Error importing plugin 'equalizer':
Traceback (most recent call last):
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/cdoersch/.local/share/rhythmbox/plugins/equalizer/equalizer.py", line 18, in <module>
    from ConfDialog import ConfDialog
  File "/home/cdoersch/.local/share/rhythmbox/plugins/equalizer/ConfDialog.py", line 20, in <module>
    import Conf
  File "/home/cdoersch/.local/share/rhythmbox/plugins/equalizer/Conf.py", line 21, in <module>
    gi.require_version('GConf', '2.0')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GConf not available

(rhythmbox:2635112): libpeas-WARNING **: 00:28:44.478: Error loading plugin 'equalizer'
```

It seems this plugin uses GConf in order to save its settings, and as of Ubuntu 20.04, GConf has been removed from python.  The plugin needs to be rewritten to use something else for persistence (probably Gio).  This shouldn't be too hard; I might do it, but would a pull request be accepted at this point?

**Comment by HubertGL** [comment]
maybe a little late, but I had just the same problem. I installed libgconf2-dev and then it worked. I am using debian bullseye, but ubuntu should be similar
